android:
  - 'android/*'
ios:
  - 'ios/*'
core/layout:
  - 'core/*'
  - 'layout/*'
demo:
  - 'demo/*'
frontend:
  - 'packages/*'
  - 'static/*'
documentation:
  - 'docs/*'
  - '**/*.js'
dependencies:
  - '**/third_party/**
