name: Build android release image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'TAG'
        default: 'latest'
        required: true
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: docker/android-release
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/android-release:${{ github.event.inputs.v8_version }}
