name: '[gh] issue translates addresses'

on: 
  issues:
    types:
      - opened

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo ${{ github.event.issue.body }}
        echo ${{ github.event.issue.title }}
        
