name: '[gh] pull review decision'

on:
  pull_request_review:
    types: [ edited, submitted ]

env:
 GREETINGS_MESSAGE: |
  :tada: It seems that this pull request has been approved by all required reviewers and only contains one normal commit.
 AUTO_MERGE_MESSAGE: |
  I will rebase and merge it automatically via `action(rebase-merge)` label.
 MANUAL_MERGE_MESSAGE: |
  I will notify admin team member to merge it manually, please wait a moment.

jobs:
  get_decision:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    outputs:
      reviewDecision: ${{ steps.decision.outputs.reviewDecision }}
    steps:
    - name: Decision
      id: decision
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          const os = require('os');

          const query = `query($owner:String!, $repo:String!, $number:Int!) {
              repository(name: $repo, owner: $owner) {
                pullRequest(number: $number) {
                  reviewDecision
                }
              }
          }`;
          const variables = {
            ...context.repo,
            number: ${{ github.event.pull_request.number }}
          };
          const { repository: { pullRequest: { reviewDecision } } } = await github.graphql(query, variables);
          if (reviewDecision === 'APPROVED' || !reviewDecision) {
            fs.appendFileSync(process.env.GITHUB_OUTPUT, `reviewDecision=APPROVED${os.EOL}`, { encoding: 'utf8' });
          }

  call_classify_commits:
    needs: get_decision
    if: needs.get_decision.outputs.reviewDecision == 'APPROVED'
    uses: ./.github/workflows/reuse_classify_commits.yml
    with:
      pull_request_number: ${{ github.event.pull_request.number }}

  auto_merge:
    needs: call_classify_commits
    if: needs.call_classify_commits.outputs.normal_commits_count == 1
    runs-on: ubuntu-latest
    steps:
    - name: Token
      uses: navikt/github-app-token-generator@v1
      id: get-token
      with:
        private-key: ${{ secrets.BOT_APP_KEY }}
        app-id: ${{ secrets.BOT_APP_ID }}
    - name: Auto
      uses: actions/github-script@v6
      with:
        github-token: ${{ steps.get-token.outputs.token }}
        script: |
          const { issues } = github.rest;

          const p = [];

          p.push(issues.addLabels({
            ...context.repo,
            issue_number: ${{ github.event.pull_request.number }},
            labels: [ 'action(rebase-merge)2' ]
          }));

          p.push(issues.createComment({
            ...context.repo,
            issue_number: ${{ github.event.pull_request.number }},
            body: process.env.GREETINGS_MESSAGE + process.env.AUTO_MERGE_MESSAGE,
          }));

          await Promise.all(p);

  manual_merge:
    needs: call_classify_commits
    if: needs.call_classify_commits.outputs.normal_commits_count > 1 || !needs.call_classify_commits.outputs.normal_commits_count
    runs-on: ubuntu-latest
    steps:
    - name: Token
      uses: navikt/github-app-token-generator@v1
      id: get-token
      with:
        private-key: ${{ secrets.BOT_APP_KEY }}
        app-id: ${{ secrets.BOT_APP_ID }}
    - name: Manual
      uses: actions/github-script@v6
      env:
        MESSAGE: |
          [#${{ github.event.pull_request.number }}](${{ github.event.pull_request.html_url }}) pull request is met merge requirements.
          > ${{ github.event.pull_request.title }}
          > <font color="warning">%s</font> commits ahead 
      with:
        github-token: ${{ steps.get-token.outputs.token }}
        script: |
          const util = require('util');
          const { issues } = github.rest;

          const p = [];

          p.push(issues.createComment({
            ...context.repo,
            issue_number: ${{ github.event.pull_request.number }},
            body: process.env.GREETINGS_MESSAGE + process.env.MANUAL_MERGE_MESSAGE
          }));

          p.push(github.request("POST ${{ secrets.WECHAT_WORK_BOT_WEBHOOK }}", {
            headers: {
              "content-type": "application/json"
            },
            data: {
              chatid: "${{ secrets.WECHAT_WORK_ADMIN_CHAT_ID }}",
              msgtype: "markdown",
              markdown: {
                content: util.format(process.env.MESSAGE, (${{ steps.comparison.outputs.ahead_by }}).toLocaleString()),
                attachments: [{
                  callback_id: "merge",
                  actions: [{
                    name: "merge_btn",
                    text: "Mark as Merged",
                    type: "button",
                    value: "Mark as Merged",
                    replace_text: "Already merged",
                    border_color: "2c974b",
                    text_color: "2c974b"
                  }, {
                    name: "ignore_btn",
                    text: "Mark as Ignored",
                    type: "button",
                    value: "Mark as Ignored",
                    replace_text: "Already ignored",
                    border_color: "6e7781",
                    text_color: "6e7781"
                  }]
                }]
              }
            }
          }));

          await Promise.all(p);
