name: 'gh_pr_review_test'

on:
  pull_request_review:
  pull_request:
    types: [ review_requested ]

jobs:
  review_test:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "${{ github.event.action }}"
        echo "${{ github.event.review.state }}"
        echo "${{ github.event.review.user.login }}"
        echo "${{ github.event.requested_reviewer.login }}"
