name: 'gh_pr_review'

on:
  pull_request:
    types: [ review_requested ]

jobs:
  review_notification:
    if: github.event.requested_reviewer.type == 'User'
    runs-on: ubuntu-latest
    steps:
    - name: Notice
      uses: actions/github-script@v6.3.3
      env:
        MESSAGE: |
          [${{ github.event.sender.login }}](https://github.com/${{ github.event.sender.login }}) requested your review on [#${{ github.event.pull_request.number }}](${{ github.event.pull_request.html_url }}) pull request.
          > ${{ github.event.pull_request.title }}
          > [${{ github.event.pull_request.html_url }}](${{ github.event.pull_request.html_url }})
          > [%s changed files](${{ github.event.pull_request.html_url }}/files) with <font color="info">%s additions</font> and <font color="warning">%s deletions</font>
      with:
        script: |
          const { format } = require("util");

          const chatid = JSON.parse("${{ secrets.WECHAT_WORK_CHAT_ID }}")["${{ github.event.requested_reviewer.login }}"];
          if (!chatid) {
            console.log("reviewer ${{ github.event.requested_reviewer.login }} not found in secrets.WECHAT_WORK_CHAT_ID");
            return;
          }

          await github.request("POST ${{ secrets.WECHAT_WORK_BOT_WEBHOOK }}", {
            headers: {
              "content-type": "application/json"
            },
            data: {
              msgtype: "markdown",
              markdown: {
                content: format(process.env.MESSAGE, (${{ github.event.pull_request.changed_files }}).toLocaleString(), (${{ github.event.pull_request.additions }}).toLocaleString(), (${{ github.event.pull_request.deletions }}).toLocaleString()),
                attachments: [{
                  callback_id: "review",
                  actions: [{
                    name: "review_btn",
                    text: "Mark as Reviewed",
                    type: "button",
                    value: "Mark as Reviewed",
                    replace_text: "Already reviewed",
                    border_color: "2c974b",
                    text_color: "2c974b"
                  }, {
                    name: "ignore_btn",
                    text: "Mark as Ignored",
                    type: "button",
                    value: "Mark as Ignored",
                    replace_text: "Already ignored",
                    border_color: "6e7781",
                    text_color: "6e7781"
                  }]
                }],
                //chatid
              }
            }
          });
