name: 'gh_pr_review'

on:
  pull_request:
    types: [ review_requested ]

jobs:
  review_notification:
    if: github.event.requested_reviewer.type == 'User'
    runs-on: ubuntu-latest
    steps:
    - name: Notice
      uses: actions/github-script@v6.3.3
      env:
        MESSAGE: |
          [${{ github.event.sender.login }}](https://github.com/${{ github.event.sender.login }}) requested your review on [#${{ github.event.pull_request.number }}](${{ github.event.pull_request.html_url }}) pull request. \n
          > ${{ github.event.pull_request.title }} \n
          > [${{ github.event.pull_request.html_url }}](${{ github.event.pull_request.html_url }}) \n
          > [${{ github.event.pull_request.changed_files }} changed files](${{ github.event.pull_request.html_url }}/files) with <font color="info">${{ github.event.pull_request.additions }} additions</font> and <font color="warning">${{ github.event.pull_request.deletions }} deletions</font>
      with:
        script: |
          await github.request("POST ${{ secrets.WECHAT_WORK_BOT_WEBHOOK }}", {
            headers: {
              "content-type": "application/json"
            },
            data: {
              msgtype: "markdown",
              markdown: {
                content: process.env.MESSAGE,
                attachments: [{
                  callback_id: "review",
                  actions: [{
                    name: "review_btn",
                    text: "Reviewed",
                    type: "button",
                    value: "Reviewed",
                    replace_text: "Already reviewed",
                    border_color: "2EAB49",
                    text_color: "2EAB49"
                  }]
                }]
              }
            }
          });
