name: '[gh] pull review decision'

on:
  pull_request_review:
    types: [ edited, submitted ]

jobs:
  get_decision:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    outputs:
      reviewDecision: ${{ steps.decision.outputs.reviewDecision }}
    steps:
    - name: Decision
      id: decision
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          const os = require('os');

          const query = `query($owner:String!, $name:String!, $number:Int!) {
              repository(name: $name, owner: $owner) {
                pullRequest(number: $number) {
                  reviewDecision
                }
              }
          }`;
          const variables = {
            owner: context.repo.owner,
            name: context.repo.repo,
            number: ${{ github.event.pull_request.number }}
          };
          const { repository: { pullRequest: { reviewDecision } } } = await github.graphql(query, variables);
          if (reviewDecision === 'APPROVED' || !reviewDecision) {
            fs.appendFileSync(process.env.GITHUB_OUTPUT, `reviewDecision=APPROVED${os.EOL}`, { encoding: 'utf8' });
          }

  call_classify_commits:
    needs: get_decision
    if: needs.get_decision.outputs.reviewDecision == 'APPROVED'
    uses: ./.github/workflows/reuse_classify_commits.yml
    with:
      pull_request_number: ${{ github.event.pull_request.number }}

  auto_merge:
    needs: call_classify_commits
    if: needs.call_classify_commits.outputs.normal_commits_count == 1
    runs-on: ubuntu-latest
    steps:
    - name: Auto
      uses: actions/github-script@v6
      with:
        script: |
          const { issues } = github.rest;

          await issues.addLabels({
            ...context.repo,
            issue_number: ${{ github.event.pull_request.number }},
            labels: [ 'action(rebase-merge)2' ]
          });

  manual_merge:
    needs: call_classify_commits
    if: needs.call_classify_commits.outputs.normal_commits_count > 1 || !needs.call_classify_commits.outputs.normal_commits_count
    runs-on: ubuntu-latest
    steps:
    - name: Manual
      uses: actions/github-script@v6
      env:
        MESSAGE: |
          [#${{ github.event.pull_request.number }}](${{ github.event.pull_request.html_url }}) pull request is met merge requirements.
          > ${{ github.event.pull_request.title }}
          > <font color="warning">%s</font> commits ahead 
      with:
        script: |
          const util = require('util');
          const { issues } = github.rest;

          await github.request("POST ${{ secrets.WECHAT_WORK_BOT_WEBHOOK }}", {
            headers: {
              "content-type": "application/json"
            },
            data: {
              chatid: "${{ secrets.WECHAT_WORK_ADMIN_CHAT_ID }}",
              msgtype: "markdown",
              markdown: {
                content: util.format(process.env.MESSAGE, (${{ steps.comparison.outputs.ahead_by }}).toLocaleString()),
                attachments: [{
                  callback_id: "merge",
                  actions: [{
                    name: "merge_btn",
                    text: "Mark as Merged",
                    type: "button",
                    value: "Mark as Merged",
                    replace_text: "Already merged",
                    border_color: "2c974b",
                    text_color: "2c974b"
                  }, {
                    name: "ignore_btn",
                    text: "Mark as Ignored",
                    type: "button",
                    value: "Mark as Ignored",
                    replace_text: "Already ignored",
                    border_color: "6e7781",
                    text_color: "6e7781"
                  }]
                }]
              }
            }
          });
