name: '[gh] pull request review target'

on:
  workflow_run:
    workflows:
      - \[gh\] pull request review triage
    types: [ completed ]

jobs:
  review_info_pull:
    runs-on: ubuntu-latest
    outputs:
      review_info: ${{ steps.info.outputs.review_info }}
    steps:
    - name: Pull
      uses: actions/github-script@v6.3.3
      with:
        script: |
          const { workflow_run } = context.payload;
          const { actions } = github.rest;
          const fs = require('fs');

          const { data: { artifacts } } = await actions.listWorkflowRunArtifacts({
             run_id: workflow_run.id,
             ...context.repo
          });
          const [ artifact ] = artifacts.filter((artifact) => {
            return artifact.name == "review_info"
          });
          if (!artifact) {
            throw new Error(`Missing review_info artifact generated in parent workflow(${workflow_run.id})`);
          }

          const download = await actions.downloadArtifact({
             artifact_id: artifact.id,
             archive_format: 'zip',
             ...context.repo
          });
          fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/review_info.zip`, Buffer.from(download.data));
    - name: Info
      id: info
      run: |
        unzip review_info.zip
        echo "review_info=$(cat review_info)" >> $GITHUB_OUTPUT

  changes_requested_comment:
    needs: review_info_pull
    runs-on: ubuntu-latest
    steps:
    - name: Token
      uses: navikt/github-app-token-generator@v1
      id: get-token
      with:
        private-key: ${{ secrets.PRIVATE_KEY }}
        app-id: ${{ secrets.APP_ID }}
    - name: Comment
      uses: actions/github-script@v6
      env:
          MESSAGE: |
            Our reviewer @%s requested changes in PR.
            If changes have been made, **click the `Re-request review` button in the right sidebar(as shown below)** to notify the reviewers.
            ![Re-request review button in the right sidebar](https://docs.github.com/assets/cb-4714/images/help/pull_requests/request-re-review.png)
          REVIEW_INFO: ${{ needs.review_info_pull.outputs.review_info }}
      with:
        github-token: ${{ steps.get-token.outputs.token }}
        script: |
          const { owner, repo } = context.repo;
          const { issues } = github.rest;
          const util = require('util');

          const review_info = JSON.parse(process.env.REVIEW_INFO);
          const { pull_request } = review_info;
          const { user } = review_info.review;

          await issues.createComment({
            issue_number: pull_request.number,
            body: util.format(process.env['MESSAGE'], user.login),
            ...context.repo
          });