name: 'gh_pr_review'

on:
  pull_request:
    types: [ review_requested ]

jobs:
  review_notification:
    if: github.event.requested_reviewer.type == 'User'
    runs-on: ubuntu-latest
    steps:
    - name: Notice
      uses: chf007/action-wechat-work@1.0.8
      env:
        WECHAT_WORK_BOT_WEBHOOK: ${{secrets.WECHAT_WORK_BOT_WEBHOOK}}
      with:
        msgtype: markdown
        content: "[${{ github.event.requested_reviewer.sender }}](https://github.com/${{ github.event.requested_reviewer.sender }}) requested your review on [#${{ github.event.pull_request.id }}](${{ github.event.pull_request.issue_url }}) pull request. \n
        > ${{ github.event.pull_request.title }} \n
        > [${{ github.event.pull_request.issue_url }}](${{ github.event.pull_request.issue_url }}) \n
        > [${{ github.event.pull_request.changed_files }} changed files](${{ github.event.pull_request.diff_url }}) with <font color="info">${{ github.event.pull_request.additions }} additions</font> and <font color="warning">${{ github.event.pull_request.deletions }} deletions</font>"
