name: '[gh] self-hosted runners monitor'

on:
  workflow_dispatch:
  schedule:
    # Run every 12th hour.
    - cron: '0 */12 * * *'

jobs:
  runners_monitor:
    runs-on: ubuntu-latest
    steps:
    - name: Token
      uses: navikt/github-app-token-generator@v1
      id: get-token
      with:
        private-key: ${{ secrets.BOT_APP_KEY }}
        app-id: ${{ secrets.BOT_APP_ID }}
    - name: Monitor
      uses: actions/github-script@v6.3.3
      with:
        github-token: ${{ steps.get-token.outputs.token }}
        script: |
          const { actions } = github.rest;

          const x = await github.paginate(actions.listSelfHostedRunnersForRepo, {
            per_page: 100,
            ...context.repo
          });

          console.log(x);