name: 'greetings'

on:
  workflow_dispatch:


jobs:
  a:
    if: 1 == 2
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo a
  b:
    if: 1 == 2
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo b
  
  c:
    needs: [ a, b ]
    if: always() && contains(needs.*.result, 'success')
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo c