name: 'greetings'

on:
  workflow_dispatch:

env:
  TEST: |
    Hello {0} World {0}

jobs:
  greetings:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "${{ format(env.TEST, 'a') }}"