name: 'greetings'

on:
  workflow_dispatch:


jobs:
  z:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo z

  a:
    needs: z
    runs-on: ubuntu-latest
    steps:
    - run: |
        exit -1
  b:
    needs: z
    if: 1 == 2
    runs-on: ubuntu-latest
    steps:
    - run: |
        sleep 10
  
  c:
    needs: [ a, b ]
    if: always()
    runs-on: ubuntu-latest
    steps:
    - if: contains(needs.*.result, 'success')
      run: |
        echo "${{ toJSON(needs.*.result) }}"
