name: Greetings

on: [workflow_dispatch]

jobs:
  greeting:
    runs-on: [self-hosted, linux]
    container:
      image: ghcr.io/medns/android-release:latest # repository name must be lowercase(${{ github.repository_owner }})
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    env:
      abc: 123
    steps:
    - run: |
        echo $abc
        