name: Greetings

on: [workflow_dispatch]

jobs:
  greeting:
    runs-on: [self-hosted, linux, trusted, test]
    container:
      image: ghcr.io/medns/android-release:latest # repository name must be lowercase(${{ github.repository_owner }})
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - run: |
        sleep 60
        