name: 'greetings'

on:
  workflow_dispatch:

jobs:
  greetings:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "hello world"
    - if: 1 == 2
      run: |
        echo "never executed"
    - if: ${{ failure() }}
      run: |
        echo "step 3"