name: 'greetings'

on:
  workflow_dispatch:

jobs:
  a:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v6.3.3
      with:
        script: |
          console.log(github.workflow);