name: 'greetings'

on:
  workflow_dispatch:


jobs:
  z:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo z

  a:
    needs: z
    if: 1 == 2
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo a
  b:
    needs: z
    runs-on: ubuntu-latest
    steps:
    - run: |
        sleep 100
        exit -1
  
  c:
    needs: [ a, b ]
    if: always() && contains(needs.*.result, 'success')
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "${{ toJSON(needs.*.result) }}"