name: 'greetings'

on:
  workflow_dispatch:


jobs:
  z:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo z

  a:
    needs: z
    runs-on: ubuntu-latest
    steps:
    - run: |
        exit -1
  b:
    needs: z
    if: 1 == 2
    runs-on: ubuntu-latest
    steps:
    - run: |
        sleep 10
  
  c:
    needs: [ a, b ]
    if: always() && (needs.a.result == 'success' || needs.b.result == 'suucess')
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "${{ toJSON(needs.*.result) }}"
        echo "${{ toJSON(contains(needs.*.result, 'success')) }}"