name: Greetings

on: [workflow_dispatch]

jobs:
  greeting:
    runs-on: ${{ github.repository == 'medns/docker-test' && 'ubuntu-latest' || fromJson('[''self-hosted'', ''linux'']') }}
    steps:
    - run: |
        echo "Hello, World!"
