name: Greetings

on: [workflow_dispatch]

jobs:
  greeting:
    runs-on: ${{ github.repository == 'nodejs/node' && 'ubuntu-latest' || ['self-hosted', 'linux'] }}
    steps:
    - run: |
        echo "Hello, World!"
