name: 'greetings'

on:
  workflow_dispatch:

jobs:
  a:
    if: 1 == 2
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo hello world

  b:
    needs: a
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo hello world