name: Greetings

on: [workflow_dispatch]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - run: |
        git clone https://github.com/tencentyun/cos-python-sdk-v5.git
        cd cos-python-sdk-v5
        python setup.py install
    - shell: python
      run: |
        from qcloud_cos import CosConfig
        print(CosConfig)
        