name: 'greetings'

on:
  workflow_dispatch:

env:
  BUILD_SCRIPT: |
    xcodebuild -workspace '{0}' -list | \
    sed -n '/Schemes/,/^$/p' | \
    grep -v "Schemes:" | \
    grep -v '^\s*$' | \
    while read scheme; do
      echo "Building ${scheme}…"
      xcodebuild build \
        -destination "generic/platform=iOS" \

jobs:
  greetings:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "${{ format(env.BUILD_SCRIPT, 'HippyDemo.xcworkspace') }}"