name: 'greetings'

on:
  workflow_dispatch:


jobs:
  z:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo z

  a:
    needs: z
    if: 1 == 2
    outputs:
      run: 'true'
    runs-on: ubuntu-latest
    steps:
    - run: |
        exit -1
  b:
    needs: z
    outputs:
      run: 'true'
    runs-on: ubuntu-latest
    steps:
    - run: |
        sleep 100
  
  c:
    needs: [ a, b ]
    if: always() && (needs.a.result == 'success' || needs.b.result == 'success') && contains(needs.*.outputs.run, 'true')
    runs-on: ubuntu-latest
    steps:
    - if: contains(needs.*.result, 'success')
      run: |
        echo "${{ toJSON(needs.*.result) }}"
