name: '[hip] list artifacts'

on:
  workflow_dispatch:
    inputs:
      hip_domain:
        description: 'HIP <domain>'
        type: choice
        options:
        - hippy
        - test
        default: 'hippy'
        required: true
      hip_path:
        description: 'HIP <path>(without domain)'
        type: string
        default: '/'
        required: true

jobs:
  list_objects:
    runs-on: ubuntu-latest
    steps:
    - name: Publish artifact
      shell: bash
      run: |
        pip install coscmd
        coscmd config -a ${{ secrets.TC_SECRET_ID }} -s ${{ secrets.TC_SECRET_KEY }} -b ${{ secrets.COS_BUCKET }} -r ${{ secrets.COS_REGION }}
        coscmd list /${{ github.event.inputs.hip_domain }}/${{ github.event.inputs.hip_path }}
    