name: '[hip] list artifacts'

on:
  workflow_dispatch:
    inputs:
      hip_domain:
        description: 'HIP <domain>'
        type: choice
        options:
        - hippy
        - test
        default: 'hippy'
        required: true
      hip_path:
        description: 'HIP <path>(without domain)'
        type: string

jobs:
  list_artifacts:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Prepare Path
      id: prepare-path
      run: |
        path=${{ github.event.inputs.hip_domain }}/${{ github.event.inputs.hip_path }}
        echo "::set-output name=path::$path"
        if [[ $path == */ ]] || [[ $path == *\\ ]]; then
          echo "::set-output name=is-directory::1"
        fi
    - name: Install Requirement
      run: |
        if [ ${{steps.prepare-path.outputs.is-directory}} == "1" ]; then
          pip install coscmd
          coscmd config -a ${{ secrets.TC_SECRET_ID }} -s ${{ secrets.TC_SECRET_KEY }} -b ${{ secrets.COS_BUCKET }} -r ${{ secrets.COS_REGION }}
        elif
          pip install -U cos-python-sdk-v5
        fi
    - name: List artifact
      if: ${{ steps.prepare-path.outputs.is-directory == '1' }}
      run: |
        coscmd list ${{ steps.prepare-path.outputs.path }} -ar >> $GITHUB_STEP_SUMMARY 2>&1
    - name: Info artifact
      if: ${{ steps.prepare-path.outputs.is-directory != '1' }}
      shell: python
      run: |
        from qcloud_cos import CosConfig
        from qcloud_cos import CosS3Client

        config = CosConfig(Region="${{ secrets.COS_REGION }}", SecretId="${{ secrets.TC_SECRET_ID }}", SecretKey="${{ secrets.TC_SECRET_KEY }}")
        client = CosS3Client(config)
        response = client.head_object(
            Bucket="${{ secrets.COS_BUCKET }}",
            Key="${{ steps.prepare-path.outputs.path }}"
        )
        print(response)
