# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      release_tag:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Person to greet'
        # Default value if no value is explicitly provided
        default: 'latest'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      v8-dist: ./android/sdk/src/main/jni/third_party/v8/{{ github.event.inputs.release_tag }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: checkout repo
      uses: actions/checkout@v2
    - name: Display structure of downloaded files
      working-directory: ${{ env.v8-dist }}
      run: ls -R
    - name: Construct directory structure
      working-directory: ${{ env.v8-dist }}
      run: |
        rm -rf official-release
        mkdir official-release
