name: '[github] pr ci example'

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo ${{ toJSON(github.event) }}