name: '[github] pr notification'

on:
  check_suite:
    types: [completed]

jobs:
  notification:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo ${{ fromJSON(github.event.check_suites) }}