name: '[gh] pull review test'

on:
  workflow_dispatch:
    inputs:
      pr:
        description: 'PR number'
        required: true
        default: '1'

jobs:
  review_notification:
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
    - name: Notice
      uses: actions/github-script@v6.3.3
      env:
        WECHAT_WORK_USERS: ${{ secrets.WECHAT_WORK_USERS }}
      with:
        script: |
          const { pulls, repos } = github.rest;
          const os = require('os');

          const { data: pr } = await pulls.get({
            ...context.repo,
            pull_number: ${{ github.event.inputs.pr }}
          });

          const { data: comparison } = await repos.compareCommitsWithBasehead({
            ...context.repo,
            basehead: `${pr.base.label}...${pr.head.label}`,
          });
          console.log(comparison.behind_by);
          
          if (comparison.behind_by > 0) {
            await pulls.updateBranch({
              ...context.repo,
              pull_number: ${{ github.event.inputs.pr }}
            });
          }

