name: '[gh] pull review test'

on:
  workflow_dispatch:

jobs:
  review_notification:
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
    - name: Notice
      uses: actions/github-script@v6.3.3
      env:
        WECHAT_WORK_USERS: ${{ secrets.WECHAT_WORK_USERS }}
      with:
        script: |
          const { pulls } = github.rest;
          const os = require('os');

          const pull_requests = await github.paginate(pulls.list, {
            per_page: 100,
            state: 'open',
            ...context.repo
          });

          console.log(JSON.stringify(pull_requests));
