name: '[gh] auto update branch'

on:
  push:
    branches:
      - 'master'

jobs:
  auto_updater:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
    - name: Updater
      uses: actions/github-script@v6.3.3
      with:
        script: |
          const { pulls, repos } = github.rest;

          const pull_requests = (await github.paginate(pulls.list, {
            per_page: 100,
            state: 'open',
            base: '${{ github.ref_name }}',
            ...context.repo
          })).filter(pull => pull.draft === false && pull.auto_merge === true);
          console.log(pull_requests);

          await Promise.all(
            pull_requests.map(pull => 
              repos.compareCommitsWithBasehead({
                ...context.repo,
                basehead: `${pull.base.label}...${pull.head.label}`,
              }).then(({ data: comparison }) => {
                if (comparison.behind_by > 0) {
                  return pulls.updateBranch({
                    ...context.repo,
                    pull_number: pull.number
                  }).catch(error => console.error(error));
                }
              })
            )
          );
